name: Fetch Database and Process

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  fetch-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout train_rnn_models repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Fetch Database Script
      run: python fetch_db.py

    - name: Add Database to Repository
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add nifty50_data_v1.db
        git commit -m "Add nifty50_data_v1.db to repository"
        git push
